### ISSUE TITLE
automated summary graf of insights

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/same-name#43]
this would go below the map, and could function like a descriptive takeaway of what is in the map/data. it could be a few sentences, essentially a visually glorified figcaption. it would be a little bit of dynamic language depending on the situation and give it some more plain language feel.

**Comment by russellsamora** [comment]
could make it dynamic, like "Although Cambridge (Canada) is the biggest place, Cambridge, MA has a combination of proximity and Wiki size to make it the most likely referenced place"

**Comment by russellsamora** [comment]
there are 23 pittsfields, it probably means MA in most places, and maybe in X (with color encoding)

**Comment by mmcghee18** [comment]
Now that i'm looking at it, I don't think you need the text description, although it could be good as just a figcaption. But i'm curious what someone with fresher eyes would think, like if the text description helps you read the map
