### ISSUE TITLE
added value of geolocating?

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/same-name#75]
currently just using it to generate curated areas to see and pre-sort + highlight county table

* add-on: highlight user location on map (though that seems to add little value and just more clutter)

**Comment by mmcghee18** [comment]
I like the curated options based on where you are, but don't think you need to show user location on the map

**Comment by iblind** [comment]
I like the idea of isolating your county (mentioned this in another issue) but not sure whether this actually adds to the experience when you're interacting with it or if it's a thing that only works conceptually
